In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [4]:
df=pd.DataFrame({'text':['People watch campusX','campusX watch campusX','People write comment','campusx write comment'],'output':[1,1,0,0]})

In [5]:
df

,text,output
0,People watch campusX,1
1,campusX watch campusX,1
2,People write comment,0
3,campusx write comment,0


In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [9]:
bow=cv.fit_transform(df['text'])

In [10]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [11]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [15]:
cv.transform(['campusX watch and write comment of campusX']).toarray()

array([[2, 1, 0, 1, 1]])